### ISSUE TITLE
Cammera monitor bug

### ISSUE THREAD

**Issue by Skratedeath** [Xperidia/FNAFGM#9]
Hello, i have a bug. In the cammera monitor i cant change cammera. There is no green button when im aiming on it with mouse. Please, fix it. I have CSS and all.

- Skratedeath.

**Comment by VictorienXP** [comment]
It's not supposed to get green by aiming @Skratedeath.

You only have to click.

I don't see any issue. The buttons works as intended. I can't reproduce your issue.

Please reopen and fill a correct bug report here or open a new issue with the correct bug report template.

**Comment by Skratedeath** [comment]
Ok, there is a video! (sorry for video glitching the glitchses is in the video)

https://www.youtube.com/watch?v=P5uRDKohc34&feature=youtu.be

**Comment by VictorienXP** [comment]
Ok so I have a few things to say, @Skratedeath.
1. You lied saying you own CSS. You're using **illegal** ways to have said game assets.
2. You have failed to read what the gamemode said.
![gamemode's message](https://user-images.githubusercontent.com/1633366/62863436-123f3b80-bd09-11e9-8071-fb93bc221991.png)

The issue you're experiencing is entirely **your fault** for using **bad behaving addons**.

Only **you** can fix this issue by **removing the bad addons** from your game.

**Comment by Skratedeath** [comment]
O.O Thank you! I am now happy! Thaankkssss!
Now i can have FNAF for free :))) !!!

**Comment by VictorienXP** [comment]
This is **not** "FNAF for free". It's only a mod for Garry's Mod that enables multiplayer. You should own the original game.
